Restore spec compliant structure of MatchCriteria
neXenio/UAF pull request #35
Opened 2018-01-30 16:55 UTC by johannesjasper

2018-01-30 17:38 UTC, Steppschuh requested changes

2018-01-30 17:38 UTC, Steppschuh commented on fido-uaf-core/src/main/java/com/nexenio/fido/uaf/core/message/MatchCriteria.java
> +    private List<String> vendorIDs;
Rename to `vendorIds` for consistency (like in `FinalChallengeParams.java`) and to meet [conventions](https://stackoverflow.com/questions/1699944/what-is-correct-java-naming-convention-for-id).

2018-01-30 17:38 UTC, Steppschuh commented on fido-uaf-core/src/main/java/com/nexenio/fido/uaf/core/message/MatchCriteria.java
> +    private List<String> keyIDs;
Rename to `keyIds`

2018-01-31 09:14 UTC, Steppschuh submitted a review, later dismissed

2018-02-02 09:18 UTC, johannesjasper commented on fido-uaf-core/src/main/java/com/nexenio/fido/uaf/core/message/MatchCriteria.java
> +    private List<Integer> attestationTypes = new ArrayList<>();
@Steppschuh  Should lists be `null` or empty?

2018-02-02 13:15 UTC, Steppschuh approved these changes

2018-02-02 13:15 UTC, Steppschuh commented on fido-uaf-core/src/main/java/com/nexenio/fido/uaf/core/message/MatchCriteria.java
> +    private int tcDisplay;
Before looking it up i didn't know that this stands for `transaction confirmation display`. Maybe we can rename that.

2018-02-02 13:16 UTC, merged